import type { Product } from "@/types";

/**
 * Demo catalogue. Used when Firebase is not configured, and as the
 * source data for `npm run seed` which uploads it to Firestore.
 */
export const demoProducts: Product[] = [
  {
    id: "bounce-pro-ball",
    name: "Bounce Pro Squeaky Ball",
    tagline: "Ultra-durable, floats in water",
    description:
      "A natural-rubber fetch ball with an internal squeaker that survives even the most enthusiastic chewers. Floats, bounces erratically and is dishwasher safe.",
    price: 8.99,
    compareAtPrice: 11.99,
    category: "Dog",
    rating: 4.8,
    reviews: 1243,
    stock: 120,
    badges: ["Bestseller"],
    features: ["Natural rubber", "Floats in water", "Dishwasher safe", "Ø 7 cm"],
    model: { kind: "ball", color: "#f97316", accent: "#ffffff" },
    videoUrl: "/videos/bounce-pro-ball.mp4",
    videoWebmUrl: "/videos/bounce-pro-ball.webm",
    videoPoster: "/videos/bounce-pro-ball.jpg",
  },
  {
    id: "dental-chew-bone",
    name: "Dental Chew Bone",
    tagline: "Cleans teeth while they play",
    description:
      "Textured nylon bone infused with chicken flavour. Ridges help reduce plaque and tartar build-up and massage gums for fresher breath.",
    price: 12.49,
    category: "Dog",
    rating: 4.6,
    reviews: 812,
    stock: 80,
    badges: ["Vet approved"],
    features: ["Chicken flavour", "Reduces plaque", "Medium & large dogs", "BPA free"],
    model: { kind: "bone", color: "#fde68a", accent: "#f59e0b" },
  },
  {
    id: "grain-free-dog-food",
    name: "Grain-Free Salmon Kibble 6kg",
    tagline: "Wild salmon & sweet potato",
    description:
      "A complete, grain-free adult dog food made with 60% wild salmon, sweet potato and botanicals. Rich in omega-3 for a glossy coat and healthy joints.",
    price: 42.99,
    compareAtPrice: 49.99,
    category: "Dog",
    rating: 4.9,
    reviews: 2109,
    stock: 45,
    badges: ["Subscribe & save 15%"],
    features: ["60% wild salmon", "Grain free", "Omega-3 & 6", "6 kg bag"],
    model: { kind: "bag", color: "#0ea5e9", accent: "#f8fafc" },
  },
  {
    id: "orthopedic-dog-bed",
    name: "Cloud Orthopaedic Dog Bed",
    tagline: "Memory foam for happy joints",
    description:
      "A plush donut bed with a memory foam base, raised bolsters and a removable, machine-washable cover. Perfect for older dogs or anyone who loves to curl up.",
    price: 64.0,
    category: "Dog",
    rating: 4.7,
    reviews: 655,
    stock: 22,
    badges: ["New"],
    features: ["Memory foam base", "Washable cover", "Non-slip bottom", "Size L"],
    model: { kind: "bed", color: "#a78bfa", accent: "#ede9fe" },
  },
  {
    id: "led-safety-collar",
    name: "Glow LED Safety Collar",
    tagline: "USB-rechargeable night visibility",
    description:
      "Stay visible on evening walks with a waterproof LED collar visible from 500 m. Three light modes and 8 hours of glow on a single USB-C charge.",
    price: 18.99,
    category: "Dog",
    rating: 4.5,
    reviews: 389,
    stock: 64,
    badges: [],
    features: ["Visible at 500 m", "USB-C rechargeable", "Waterproof", "Adjustable fit"],
    model: { kind: "collar", color: "#22c55e", accent: "#bbf7d0" },
  },
  {
    id: "robo-mouse-toy",
    name: "RoboMouse Interactive Cat Toy",
    tagline: "Self-moving, obstacle-sensing",
    description:
      "A motion-activated robotic mouse that scurries, changes direction and avoids obstacles to trigger your cat's hunting instinct. Auto-sleeps to save battery.",
    price: 24.99,
    compareAtPrice: 29.99,
    category: "Cat",
    rating: 4.4,
    reviews: 978,
    stock: 50,
    badges: ["Trending"],
    features: ["Smart obstacle sensing", "USB rechargeable", "Feather tail", "Auto sleep"],
    model: { kind: "mouse", color: "#9ca3af", accent: "#f9a8d4" },
  },
  {
    id: "sky-cat-tree",
    name: "Sky Tower Cat Tree",
    tagline: "Three levels of climbing fun",
    description:
      "A sturdy 120 cm cat tree with sisal-wrapped scratching posts, a cosy hideaway and a top perch for keeping an eye on the household.",
    price: 89.99,
    category: "Cat",
    rating: 4.8,
    reviews: 501,
    stock: 15,
    badges: ["Bestseller"],
    features: ["120 cm tall", "Sisal posts", "Plush hideaway", "Easy assembly"],
    model: { kind: "tower", color: "#d6d3d1", accent: "#78716c" },
  },
  {
    id: "ceramic-slow-bowl",
    name: "Ceramic Slow-Feeder Bowl",
    tagline: "Slows gulping by 10x",
    description:
      "Hand-glazed ceramic bowl with a raised maze to slow down fast eaters, reducing bloating and improving digestion. Heavy base won't slide around.",
    price: 16.5,
    category: "Cat",
    rating: 4.6,
    reviews: 432,
    stock: 70,
    badges: [],
    features: ["Food-safe ceramic", "Anti-slip base", "Dishwasher safe", "500 ml"],
    model: { kind: "bowl", color: "#f43f5e", accent: "#fff1f2" },
  },
  {
    id: "oatmeal-shampoo",
    name: "Soothing Oatmeal Shampoo",
    tagline: "For sensitive, itchy skin",
    description:
      "A gentle, soap-free shampoo with colloidal oatmeal and aloe vera that calms irritated skin and leaves coats soft and shiny. Suitable for dogs and cats.",
    price: 9.99,
    category: "Health",
    rating: 4.7,
    reviews: 744,
    stock: 95,
    badges: ["Vet approved"],
    features: ["Soap free", "Colloidal oatmeal", "pH balanced", "500 ml"],
    model: { kind: "bottle", color: "#14b8a6", accent: "#f0fdfa" },
  },
  {
    id: "travel-pet-carrier",
    name: "Explorer Travel Carrier",
    tagline: "Airline-approved comfort",
    description:
      "A ventilated, hard-shell carrier with a top-loading door, padded mat and seat-belt loop. Airline-approved for cabin travel with small pets.",
    price: 54.99,
    category: "Cat",
    rating: 4.5,
    reviews: 268,
    stock: 30,
    badges: [],
    features: ["Airline approved", "Top & front doors", "Ventilated", "Up to 8 kg"],
    model: { kind: "carrier", color: "#3b82f6", accent: "#e5e7eb" },
  },
  {
    id: "aqua-starter-bowl",
    name: "Aqua Starter Fish Bowl",
    tagline: "LED-lit 15 L aquarium",
    description:
      "A seamless glass bowl with built-in LED lighting and a whisper-quiet filter. Everything you need to start a beautiful home for your fish.",
    price: 39.99,
    category: "Fish",
    rating: 4.3,
    reviews: 187,
    stock: 18,
    badges: ["New"],
    features: ["15 litres", "LED lighting", "Quiet filter", "Glass bowl"],
    model: { kind: "fishbowl", color: "#38bdf8", accent: "#fb923c" },
  },
  {
    id: "cosy-rabbit-hutch",
    name: "Cosy Two-Storey Hutch",
    tagline: "Weatherproof home for rabbits",
    description:
      "A solid fir-wood hutch with a sheltered bedroom, ramp, and a pull-out tray for easy cleaning. Treated to withstand the British weather.",
    price: 129.0,
    compareAtPrice: 149.0,
    category: "Small Pet",
    rating: 4.6,
    reviews: 143,
    stock: 9,
    badges: ["Low stock"],
    features: ["Solid fir wood", "Weatherproof roof", "Pull-out tray", "Ramp included"],
    model: { kind: "hutch", color: "#b45309", accent: "#365314" },
  },
];

export const categories = ["All", "Dog", "Cat", "Small Pet", "Fish", "Health"] as const;
